//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BilWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class event_descriptions
    {
        public int event_type_id { get; set; }
        public string language { get; set; }
        public string title { get; set; }
        public string description { get; set; }
    
        public virtual event_types event_types { get; set; }
    }
}
